// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: playlist.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addPlaylistItem = `-- name: AddPlaylistItem :one
WITH max_pos AS (
    SELECT COALESCE(MAX(position), 0) AS position
    FROM playlist_items 
    WHERE playlist_id = $1
)
INSERT INTO playlist_items (
    playlist_id, video_id, position
) VALUES (
    $1, 
    $2, 
    CASE WHEN $3 > 0 THEN $3 ELSE (SELECT position + 1 FROM max_pos) END
)
RETURNING id, playlist_id, video_id, position, added_at
`

type AddPlaylistItemParams struct {
	PlaylistID uuid.UUID   `json:"playlist_id"`
	VideoID    string      `json:"video_id"`
	Column3    interface{} `json:"column_3"`
}

func (q *Queries) AddPlaylistItem(ctx context.Context, arg AddPlaylistItemParams) (PlaylistItem, error) {
	row := q.db.QueryRow(ctx, addPlaylistItem, arg.PlaylistID, arg.VideoID, arg.Column3)
	var i PlaylistItem
	err := row.Scan(
		&i.ID,
		&i.PlaylistID,
		&i.VideoID,
		&i.Position,
		&i.AddedAt,
	)
	return i, err
}

const createPlaylist = `-- name: CreatePlaylist :one
INSERT INTO playlists (
    owner_id, title, description, visibility
) VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, title, description, visibility, thumbnail_url, created_at, updated_at, video_count
`

type CreatePlaylistParams struct {
	OwnerID     string      `json:"owner_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Visibility  Visibility  `json:"visibility"`
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error) {
	row := q.db.QueryRow(ctx, createPlaylist,
		arg.OwnerID,
		arg.Title,
		arg.Description,
		arg.Visibility,
	)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Visibility,
		&i.ThumbnailUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VideoCount,
	)
	return i, err
}

const decrementVideoCount = `-- name: DecrementVideoCount :exec
UPDATE playlists
SET video_count = video_count - 1
WHERE id = $1
`

func (q *Queries) DecrementVideoCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementVideoCount, id)
	return err
}

const deletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM playlists
WHERE id = $1
`

func (q *Queries) DeletePlaylist(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlaylist, id)
	return err
}

const getPlaylist = `-- name: GetPlaylist :one
SELECT id, owner_id, title, description, visibility, thumbnail_url, created_at, updated_at, video_count FROM playlists 
WHERE id = $1
`

func (q *Queries) GetPlaylist(ctx context.Context, id uuid.UUID) (Playlist, error) {
	row := q.db.QueryRow(ctx, getPlaylist, id)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Visibility,
		&i.ThumbnailUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VideoCount,
	)
	return i, err
}

const incrementVideoCount = `-- name: IncrementVideoCount :exec
UPDATE playlists
SET video_count = video_count + 1
WHERE id = $1
`

func (q *Queries) IncrementVideoCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementVideoCount, id)
	return err
}

const listPlaylistItems = `-- name: ListPlaylistItems :many
SELECT id, playlist_id, video_id, position, added_at FROM playlist_items
WHERE playlist_id = $1
ORDER BY position
LIMIT $2 OFFSET $3
`

type ListPlaylistItemsParams struct {
	PlaylistID uuid.UUID `json:"playlist_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListPlaylistItems(ctx context.Context, arg ListPlaylistItemsParams) ([]PlaylistItem, error) {
	rows, err := q.db.Query(ctx, listPlaylistItems, arg.PlaylistID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlaylistItem{}
	for rows.Next() {
		var i PlaylistItem
		if err := rows.Scan(
			&i.ID,
			&i.PlaylistID,
			&i.VideoID,
			&i.Position,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylists = `-- name: ListPlaylists :many

SELECT id, owner_id, title, description, visibility, thumbnail_url, created_at, updated_at, video_count FROM playlists
WHERE 
    CASE WHEN $3::text IS NOT NULL AND $3::text != '' AND $3::text != 'ALL' THEN
        visibility = $3::visibility
    ELSE
        TRUE
    END
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListPlaylistsParams struct {
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
	Column3 string `json:"column_3"`
}

// -- name: ListPlaylists :many
// SELECT * FROM playlists
// WHERE
//
//	CASE WHEN $3::text != 'ALL' THEN
//	    visibility = $3::visibility
//	ELSE
//	    TRUE
//	END
//
// ORDER BY created_at DESC
// LIMIT $1
// OFFSET $2;
func (q *Queries) ListPlaylists(ctx context.Context, arg ListPlaylistsParams) ([]Playlist, error) {
	rows, err := q.db.Query(ctx, listPlaylists, arg.Limit, arg.Offset, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Playlist{}
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Description,
			&i.Visibility,
			&i.ThumbnailUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VideoCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const movePlaylistItem = `-- name: MovePlaylistItem :one
WITH item AS (
    SELECT position FROM playlist_items
    WHERE id = $2 AND playlist_id = $1
)
UPDATE playlist_items pi
SET position = 
    CASE 
        WHEN pi.id = $2 THEN $3
        WHEN pi.position >= $3 AND pi.position < (SELECT position FROM item) 
            THEN pi.position + 1
        WHEN pi.position <= $3 AND pi.position > (SELECT position FROM item) 
            THEN pi.position - 1
        ELSE pi.position
    END
WHERE pi.playlist_id = $1
RETURNING pi.id, pi.playlist_id, pi.video_id, pi.position, pi.added_at
`

type MovePlaylistItemParams struct {
	PlaylistID uuid.UUID `json:"playlist_id"`
	ID         uuid.UUID `json:"id"`
	Position   int32     `json:"position"`
}

func (q *Queries) MovePlaylistItem(ctx context.Context, arg MovePlaylistItemParams) (PlaylistItem, error) {
	row := q.db.QueryRow(ctx, movePlaylistItem, arg.PlaylistID, arg.ID, arg.Position)
	var i PlaylistItem
	err := row.Scan(
		&i.ID,
		&i.PlaylistID,
		&i.VideoID,
		&i.Position,
		&i.AddedAt,
	)
	return i, err
}

const removePlaylistItem = `-- name: RemovePlaylistItem :exec
DELETE FROM playlist_items
WHERE playlist_id = $1 AND id = $2
`

type RemovePlaylistItemParams struct {
	PlaylistID uuid.UUID `json:"playlist_id"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) RemovePlaylistItem(ctx context.Context, arg RemovePlaylistItemParams) error {
	_, err := q.db.Exec(ctx, removePlaylistItem, arg.PlaylistID, arg.ID)
	return err
}

const updatePlaylist = `-- name: UpdatePlaylist :one
UPDATE playlists
SET
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    visibility = COALESCE($4, visibility),
    updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, title, description, visibility, thumbnail_url, created_at, updated_at, video_count
`

type UpdatePlaylistParams struct {
	ID          uuid.UUID   `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Visibility  Visibility  `json:"visibility"`
}

func (q *Queries) UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (Playlist, error) {
	row := q.db.QueryRow(ctx, updatePlaylist,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Visibility,
	)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Description,
		&i.Visibility,
		&i.ThumbnailUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VideoCount,
	)
	return i, err
}
