// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: storage.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVideoStorage = `-- name: CreateVideoStorage :one
INSERT INTO video_storage (
  id, video_id, file_name, file_size, storage_path, manifest_path
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, video_id, file_name, file_size, storage_path, created_at, updated_at, manifest_path
`

type CreateVideoStorageParams struct {
	ID           uuid.UUID   `json:"id"`
	VideoID      string      `json:"video_id"`
	FileName     string      `json:"file_name"`
	FileSize     pgtype.Int8 `json:"file_size"`
	StoragePath  string      `json:"storage_path"`
	ManifestPath pgtype.Text `json:"manifest_path"`
}

// Video Storage Queries
func (q *Queries) CreateVideoStorage(ctx context.Context, arg CreateVideoStorageParams) (VideoStorage, error) {
	row := q.db.QueryRow(ctx, createVideoStorage,
		arg.ID,
		arg.VideoID,
		arg.FileName,
		arg.FileSize,
		arg.StoragePath,
		arg.ManifestPath,
	)
	var i VideoStorage
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.FileName,
		&i.FileSize,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManifestPath,
	)
	return i, err
}

const deleteVideoStorage = `-- name: DeleteVideoStorage :exec
DELETE FROM video_storage 
WHERE video_id = $1
`

func (q *Queries) DeleteVideoStorage(ctx context.Context, videoID string) error {
	_, err := q.db.Exec(ctx, deleteVideoStorage, videoID)
	return err
}

const getVideoStorage = `-- name: GetVideoStorage :one
SELECT
  id,
  video_id,
  file_name,
  file_size,
  storage_path,
  manifest_path
FROM video_storage
WHERE video_id = $1
`

type GetVideoStorageRow struct {
	ID           uuid.UUID   `json:"id"`
	VideoID      string      `json:"video_id"`
	FileName     string      `json:"file_name"`
	FileSize     pgtype.Int8 `json:"file_size"`
	StoragePath  string      `json:"storage_path"`
	ManifestPath pgtype.Text `json:"manifest_path"`
}

func (q *Queries) GetVideoStorage(ctx context.Context, videoID string) (GetVideoStorageRow, error) {
	row := q.db.QueryRow(ctx, getVideoStorage, videoID)
	var i GetVideoStorageRow
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.FileName,
		&i.FileSize,
		&i.StoragePath,
		&i.ManifestPath,
	)
	return i, err
}

const updateVideoStorage = `-- name: UpdateVideoStorage :one
UPDATE video_storage SET
  file_name = $2,
  file_size = $3,
  storage_path = $4,
  manifest_path = $5,
  updated_at = now()
WHERE id = $1
RETURNING id, video_id, file_name, file_size, storage_path, created_at, updated_at, manifest_path
`

type UpdateVideoStorageParams struct {
	ID           uuid.UUID   `json:"id"`
	FileName     string      `json:"file_name"`
	FileSize     pgtype.Int8 `json:"file_size"`
	StoragePath  string      `json:"storage_path"`
	ManifestPath pgtype.Text `json:"manifest_path"`
}

func (q *Queries) UpdateVideoStorage(ctx context.Context, arg UpdateVideoStorageParams) (VideoStorage, error) {
	row := q.db.QueryRow(ctx, updateVideoStorage,
		arg.ID,
		arg.FileName,
		arg.FileSize,
		arg.StoragePath,
		arg.ManifestPath,
	)
	var i VideoStorage
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.FileName,
		&i.FileSize,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManifestPath,
	)
	return i, err
}

const updateVideoStorageManifest = `-- name: UpdateVideoStorageManifest :one
UPDATE video_storage SET
  manifest_path = $2,
  updated_at = now()
WHERE id = $1
RETURNING id, video_id, file_name, file_size, storage_path, created_at, updated_at, manifest_path
`

type UpdateVideoStorageManifestParams struct {
	ID           uuid.UUID   `json:"id"`
	ManifestPath pgtype.Text `json:"manifest_path"`
}

func (q *Queries) UpdateVideoStorageManifest(ctx context.Context, arg UpdateVideoStorageManifestParams) (VideoStorage, error) {
	row := q.db.QueryRow(ctx, updateVideoStorageManifest, arg.ID, arg.ManifestPath)
	var i VideoStorage
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.FileName,
		&i.FileSize,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManifestPath,
	)
	return i, err
}
