// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sub.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSubCategory = `-- name: CreateSubCategory :one
INSERT INTO "sub_categories" ("id", "category_id", "name")
VALUES ($1, $2, $3)
RETURNING id, category_id, name, name_tsvector
`

type CreateSubCategoryParams struct {
	ID         uuid.UUID `json:"id"`
	CategoryID uuid.UUID `json:"category_id"`
	Name       string    `json:"name"`
}

// Insert a new sub-category
func (q *Queries) CreateSubCategory(ctx context.Context, arg CreateSubCategoryParams) (SubCategory, error) {
	row := q.db.QueryRow(ctx, createSubCategory, arg.ID, arg.CategoryID, arg.Name)
	var i SubCategory
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.NameTsvector,
	)
	return i, err
}

const deleteSubCategory = `-- name: DeleteSubCategory :exec
DELETE FROM "sub_categories"
WHERE "id" = $1
`

// Delete a sub-category by ID
func (q *Queries) DeleteSubCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubCategory, id)
	return err
}

const getSubCategoriesByCategoryID = `-- name: GetSubCategoriesByCategoryID :many
SELECT id, category_id, name, name_tsvector FROM "sub_categories"
WHERE "category_id" = $1
`

// Get all sub-categories by category ID
func (q *Queries) GetSubCategoriesByCategoryID(ctx context.Context, categoryID uuid.UUID) ([]SubCategory, error) {
	rows, err := q.db.Query(ctx, getSubCategoriesByCategoryID, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubCategory{}
	for rows.Next() {
		var i SubCategory
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.NameTsvector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubCategoryByID = `-- name: GetSubCategoryByID :one
SELECT id, category_id, name, name_tsvector FROM "sub_categories"
WHERE "id" = $1
`

// Get a sub-category by ID
func (q *Queries) GetSubCategoryByID(ctx context.Context, id uuid.UUID) (SubCategory, error) {
	row := q.db.QueryRow(ctx, getSubCategoryByID, id)
	var i SubCategory
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.NameTsvector,
	)
	return i, err
}

const updateSubCategory = `-- name: UpdateSubCategory :one
UPDATE "sub_categories"
SET "name" = $2
WHERE "id" = $1
RETURNING id, category_id, name, name_tsvector
`

type UpdateSubCategoryParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// Update a sub-category's details
func (q *Queries) UpdateSubCategory(ctx context.Context, arg UpdateSubCategoryParams) (SubCategory, error) {
	row := q.db.QueryRow(ctx, updateSubCategory, arg.ID, arg.Name)
	var i SubCategory
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.NameTsvector,
	)
	return i, err
}
