// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: video_metadata.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVideoMetadata = `-- name: CreateVideoMetadata :one

INSERT INTO video_metadata (
  id,
  video_id,
  thumbnail_path,
  sprite_path,
  vtt_path, 
  preview_path
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, video_id, thumbnail_path, gif_path, sprite_path, vtt_path, preview_path
`

type CreateVideoMetadataParams struct {
	ID            uuid.UUID   `json:"id"`
	VideoID       string      `json:"video_id"`
	ThumbnailPath pgtype.Text `json:"thumbnail_path"`
	SpritePath    pgtype.Text `json:"sprite_path"`
	VttPath       pgtype.Text `json:"vtt_path"`
	PreviewPath   pgtype.Text `json:"preview_path"`
}

// File: db/query/video_metadata.sql
func (q *Queries) CreateVideoMetadata(ctx context.Context, arg CreateVideoMetadataParams) (VideoMetadatum, error) {
	row := q.db.QueryRow(ctx, createVideoMetadata,
		arg.ID,
		arg.VideoID,
		arg.ThumbnailPath,
		arg.SpritePath,
		arg.VttPath,
		arg.PreviewPath,
	)
	var i VideoMetadatum
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.ThumbnailPath,
		&i.GifPath,
		&i.SpritePath,
		&i.VttPath,
		&i.PreviewPath,
	)
	return i, err
}

const deleteVideoMetadata = `-- name: DeleteVideoMetadata :exec
DELETE FROM video_metadata
WHERE video_id = $1
`

func (q *Queries) DeleteVideoMetadata(ctx context.Context, videoID string) error {
	_, err := q.db.Exec(ctx, deleteVideoMetadata, videoID)
	return err
}

const getVideoMetadata = `-- name: GetVideoMetadata :one
SELECT
  id,
  video_id,
  thumbnail_path,
  sprite_path,
  vtt_path,
  gif_path,
  preview_path
FROM video_metadata
WHERE video_id = $1
LIMIT 1
`

type GetVideoMetadataRow struct {
	ID            uuid.UUID   `json:"id"`
	VideoID       string      `json:"video_id"`
	ThumbnailPath pgtype.Text `json:"thumbnail_path"`
	SpritePath    pgtype.Text `json:"sprite_path"`
	VttPath       pgtype.Text `json:"vtt_path"`
	GifPath       pgtype.Text `json:"gif_path"`
	PreviewPath   pgtype.Text `json:"preview_path"`
}

func (q *Queries) GetVideoMetadata(ctx context.Context, videoID string) (GetVideoMetadataRow, error) {
	row := q.db.QueryRow(ctx, getVideoMetadata, videoID)
	var i GetVideoMetadataRow
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.ThumbnailPath,
		&i.SpritePath,
		&i.VttPath,
		&i.GifPath,
		&i.PreviewPath,
	)
	return i, err
}

const updateVideoMetadata = `-- name: UpdateVideoMetadata :one
UPDATE video_metadata
SET
  thumbnail_path = $2,
  sprite_path    = $3,
  vtt_path       = $4,
  gif_path       = $5,
  preview_path   = $6
WHERE video_id = $1
RETURNING id, video_id, thumbnail_path, gif_path, sprite_path, vtt_path, preview_path
`

type UpdateVideoMetadataParams struct {
	VideoID       string      `json:"video_id"`
	ThumbnailPath pgtype.Text `json:"thumbnail_path"`
	SpritePath    pgtype.Text `json:"sprite_path"`
	VttPath       pgtype.Text `json:"vtt_path"`
	GifPath       pgtype.Text `json:"gif_path"`
	PreviewPath   pgtype.Text `json:"preview_path"`
}

func (q *Queries) UpdateVideoMetadata(ctx context.Context, arg UpdateVideoMetadataParams) (VideoMetadatum, error) {
	row := q.db.QueryRow(ctx, updateVideoMetadata,
		arg.VideoID,
		arg.ThumbnailPath,
		arg.SpritePath,
		arg.VttPath,
		arg.GifPath,
		arg.PreviewPath,
	)
	var i VideoMetadatum
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.ThumbnailPath,
		&i.GifPath,
		&i.SpritePath,
		&i.VttPath,
		&i.PreviewPath,
	)
	return i, err
}
