// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: videos.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVideo = `-- name: CreateVideo :exec


INSERT INTO videos (id, title, description, duration, channel_id, total_segment)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateVideoParams struct {
	ID           string          `json:"id"`
	Title        string          `json:"title"`
	Description  pgtype.Text     `json:"description"`
	Duration     pgtype.Interval `json:"duration"`
	ChannelID    string          `json:"channel_id"`
	TotalSegment int32           `json:"total_segment"`
}

// -- Updated GetVideos query
// -- name: GetVideo :many
// SELECT
//
//	id,
//	total_segment,
//	received_s,
//	title,
//	status,
//	visibility,
//	description,
//	uploaded_at,
//	(EXTRACT(EPOCH FROM duration) * 1000000000)::BIGINT AS duration_ns,
//	views,
//	likes,
//	dislikes,
//	channel_id
//
// FROM videos
// LIMIT $1
// OFFSET $2;
// Similarly update GetVideosByChannelID and other queries
func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) error {
	_, err := q.db.Exec(ctx, createVideo,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Duration,
		arg.ChannelID,
		arg.TotalSegment,
	)
	return err
}

const deleteVideo = `-- name: DeleteVideo :exec
DELETE FROM "videos"
WHERE "id" = $1
`

// Delete a video
func (q *Queries) DeleteVideo(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteVideo, id)
	return err
}

const editVideoWithMask = `-- name: EditVideoWithMask :exec
UPDATE videos
SET
  title = CASE WHEN $1::boolean THEN $2 ELSE title END,
  visibility = CASE WHEN $3::boolean THEN $4 ELSE visibility END,
  description = CASE WHEN $5::boolean THEN $6 ELSE description END
WHERE id = $7
`

type EditVideoWithMaskParams struct {
	SetTitle       bool        `json:"set_title"`
	Title          string      `json:"title"`
	SetVisibility  bool        `json:"set_visibility"`
	Visibility     Visibility  `json:"visibility"`
	SetDescription bool        `json:"set_description"`
	Description    pgtype.Text `json:"description"`
	ID             string      `json:"id"`
}

func (q *Queries) EditVideoWithMask(ctx context.Context, arg EditVideoWithMaskParams) error {
	_, err := q.db.Exec(ctx, editVideoWithMask,
		arg.SetTitle,
		arg.Title,
		arg.SetVisibility,
		arg.Visibility,
		arg.SetDescription,
		arg.Description,
		arg.ID,
	)
	return err
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT id, 
  title, 
  description, 
  duration, 
  channel_id, 
  total_segment, 
  likes, 
  dislikes, 
  views, 
  uploaded_at
FROM videos
WHERE id = $1
`

type GetVideoByIDRow struct {
	ID           string          `json:"id"`
	Title        string          `json:"title"`
	Description  pgtype.Text     `json:"description"`
	Duration     pgtype.Interval `json:"duration"`
	ChannelID    string          `json:"channel_id"`
	TotalSegment int32           `json:"total_segment"`
	Likes        int64           `json:"likes"`
	Dislikes     int64           `json:"dislikes"`
	Views        int64           `json:"views"`
	UploadedAt   time.Time       `json:"uploaded_at"`
}

func (q *Queries) GetVideoByID(ctx context.Context, id string) (GetVideoByIDRow, error) {
	row := q.db.QueryRow(ctx, getVideoByID, id)
	var i GetVideoByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Duration,
		&i.ChannelID,
		&i.TotalSegment,
		&i.Likes,
		&i.Dislikes,
		&i.Views,
		&i.UploadedAt,
	)
	return i, err
}

const getVideoRowByID = `-- name: GetVideoRowByID :one

SELECT 
  id,
  total_segment,
  received_s,
  title,
  status,
  visibility,
  description,
  uploaded_at,
  (EXTRACT(EPOCH FROM duration) * 1000000000)::BIGINT AS duration_ns,
  views,
  likes,
  dislikes,
  channel_id
FROM videos
WHERE id = $1
`

type GetVideoRowByIDRow struct {
	ID           string          `json:"id"`
	TotalSegment int32           `json:"total_segment"`
	ReceivedS    int32           `json:"received_s"`
	Title        string          `json:"title"`
	Status       NullVideoStatus `json:"status"`
	Visibility   Visibility      `json:"visibility"`
	Description  pgtype.Text     `json:"description"`
	UploadedAt   time.Time       `json:"uploaded_at"`
	DurationNs   int64           `json:"duration_ns"`
	Views        int64           `json:"views"`
	Likes        int64           `json:"likes"`
	Dislikes     int64           `json:"dislikes"`
	ChannelID    string          `json:"channel_id"`
}

// -- name: GetVideoByID :one
// SELECT * FROM videos WHERE id = $1;
func (q *Queries) GetVideoRowByID(ctx context.Context, id string) (GetVideoRowByIDRow, error) {
	row := q.db.QueryRow(ctx, getVideoRowByID, id)
	var i GetVideoRowByIDRow
	err := row.Scan(
		&i.ID,
		&i.TotalSegment,
		&i.ReceivedS,
		&i.Title,
		&i.Status,
		&i.Visibility,
		&i.Description,
		&i.UploadedAt,
		&i.DurationNs,
		&i.Views,
		&i.Likes,
		&i.Dislikes,
		&i.ChannelID,
	)
	return i, err
}

const getVideosByChannelID = `-- name: GetVideosByChannelID :many
SELECT 
  id,
  total_segment,
  received_s,
  title,
  status,
  visibility,
  description,
  uploaded_at,
  (EXTRACT(EPOCH FROM duration) * 1000000000)::BIGINT AS duration_ns,
  views,
  likes,
  dislikes,
  channel_id
FROM videos
WHERE "channel_id" = $1
ORDER BY RANDOM() -- or ORDER BY "uploaded_at" DESC
LIMIT $2 OFFSET $3
`

type GetVideosByChannelIDParams struct {
	ChannelID string `json:"channel_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type GetVideosByChannelIDRow struct {
	ID           string          `json:"id"`
	TotalSegment int32           `json:"total_segment"`
	ReceivedS    int32           `json:"received_s"`
	Title        string          `json:"title"`
	Status       NullVideoStatus `json:"status"`
	Visibility   Visibility      `json:"visibility"`
	Description  pgtype.Text     `json:"description"`
	UploadedAt   time.Time       `json:"uploaded_at"`
	DurationNs   int64           `json:"duration_ns"`
	Views        int64           `json:"views"`
	Likes        int64           `json:"likes"`
	Dislikes     int64           `json:"dislikes"`
	ChannelID    string          `json:"channel_id"`
}

// Get all videos by channel ID with pagination
// Updated GetVideos query
func (q *Queries) GetVideosByChannelID(ctx context.Context, arg GetVideosByChannelIDParams) ([]GetVideosByChannelIDRow, error) {
	rows, err := q.db.Query(ctx, getVideosByChannelID, arg.ChannelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVideosByChannelIDRow{}
	for rows.Next() {
		var i GetVideosByChannelIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TotalSegment,
			&i.ReceivedS,
			&i.Title,
			&i.Status,
			&i.Visibility,
			&i.Description,
			&i.UploadedAt,
			&i.DurationNs,
			&i.Views,
			&i.Likes,
			&i.Dislikes,
			&i.ChannelID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideosWithKeywordFilter = `-- name: GetVideosWithKeywordFilter :many







SELECT
    v.id,
    v.title,
    v.views,
    (EXTRACT(EPOCH FROM duration) * 1000000000)::BIGINT AS duration_ns,
    v.uploaded_at,
    c.id AS channel_id,
    c.name AS channel_name
FROM (
    SELECT v.id
    FROM videos v
    JOIN channels c ON c.id = v.channel_id
    WHERE v.visibility = 'public' AND v.status = 'processed'
      AND (
        COALESCE(TRIM($1), '') IN ('', 'All')
        OR v.title_tsvector @@ plainto_tsquery('english', $1)
        OR c.name_tsvector @@ plainto_tsquery('english', $1)
        OR EXISTS (
            SELECT 1 FROM videotag vt
            JOIN tag t ON t.id = vt.tag_id
            WHERE vt.video_id = v.id
            AND t.tag_tsvector @@ plainto_tsquery('english', $1)
        )
        OR EXISTS (
            SELECT 1 FROM video_categories vc
            JOIN categories cat ON cat.id = vc.category_id
            WHERE vc.video_id = v.id
            AND cat.name_tsvector @@ plainto_tsquery('english', $1)
        )
        OR EXISTS (
            SELECT 1 FROM video_categories vc
            JOIN sub_categories sc ON sc.id = vc.sub_category_id
            WHERE vc.video_id = v.id
            AND sc.name_tsvector @@ plainto_tsquery('english', $1)
        )
      )
    ORDER BY md5(v.id::text || $4)  -- Consistent seeded ordering
    LIMIT $2 OFFSET $3
) AS sub
JOIN videos v ON v.id = sub.id
JOIN channels c ON c.id = v.channel_id
`

type GetVideosWithKeywordFilterParams struct {
	Btrim  string `json:"btrim"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	ID     string `json:"id"`
}

type GetVideosWithKeywordFilterRow struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Views       int64     `json:"views"`
	DurationNs  int64     `json:"duration_ns"`
	UploadedAt  time.Time `json:"uploaded_at"`
	ChannelID   string    `json:"channel_id"`
	ChannelName string    `json:"channel_name"`
}

// -- name: GetVideosWithKeywordFilter :many
// SELECT
//
//	v.id,
//	v.title,
//	v.views,
//	v.duration,
//	v.uploaded_at,
//	c.id   AS channel_id,
//	c.name AS channel_name
//
// FROM (
//
//	SELECT v.id
//	FROM videos v
//	JOIN channels c ON c.id = v.channel_id
//	LEFT JOIN videotag vt       ON vt.video_id = v.id
//	LEFT JOIN tag t             ON t.id = vt.tag_id
//	LEFT JOIN video_categories vc ON vc.video_id = v.id
//	LEFT JOIN categories cat    ON cat.id = vc.category_id
//	LEFT JOIN sub_categories sc ON sc.id  = vc.sub_category_id
//	WHERE v.visibility = 'public'
//	  AND (
//	    -- no filter: empty or "All"
//	    $1 = ''
//	    OR $1 = 'All'
//	    -- title, channel name
//	    OR LOWER(v.title)   LIKE LOWER('%' || $1 || '%')
//	    OR LOWER(c.name)    LIKE LOWER('%' || $1 || '%')
//	    -- tags
//	    OR EXISTS (
//	      SELECT 1
//	      FROM videotag vt2
//	      JOIN tag t2 ON t2.id = vt2.tag_id
//	      WHERE vt2.video_id = v.id
//	        AND LOWER(t2.tag) LIKE LOWER('%' || $1 || '%')
//	    )
//	    -- categories
//	    OR EXISTS (
//	      SELECT 1
//	      FROM video_categories vc2
//	      JOIN categories cat2 ON cat2.id = vc2.category_id
//	      WHERE vc2.video_id = v.id
//	        AND LOWER(cat2.name) LIKE LOWER('%' || $1 || '%')
//	    )
//	    -- sub-categories
//	    OR EXISTS (
//	      SELECT 1
//	      FROM video_categories vc3
//	      JOIN sub_categories sc2 ON sc2.id = vc3.sub_category_id
//	      WHERE vc3.video_id = v.id
//	        AND LOWER(sc2.name) LIKE LOWER('%' || $1 || '%')
//	    )
//	  )
//	ORDER BY random()
//	LIMIT $2
//	OFFSET $3
//
// ) AS sub
// JOIN videos v   ON v.id = sub.id
// JOIN channels c ON c.id = v.channel_id;
// -- name: GetVideosWithKeywordFilters :many
// SELECT
//
//	v.id,
//	v.title,
//	v.views,
//	v.duration,
//	v.uploaded_at,
//	c.id AS channel_id,
//	c.name AS channel_name
//
// FROM (
//
//	SELECT v.id
//	FROM videos v
//	JOIN channels c ON c.id = v.channel_id
//	WHERE v.visibility = 'public'
//	  AND (
//	    COALESCE(TRIM($1), '') IN ('', 'All')
//	    OR LOWER(v.title) LIKE '%' || LOWER(TRIM($1)) || '%'
//	    OR LOWER(c.name)  LIKE '%' || LOWER(TRIM($1)) || '%'
//	    OR (
//	      EXISTS (
//	        SELECT 1 FROM videotag vt
//	        JOIN tag t ON t.id = vt.tag_id
//	        WHERE vt.video_id = v.id
//	          AND LOWER(t.tag) LIKE '%' || LOWER(TRIM($1)) || '%'
//	      )
//	    )
//	    OR (
//	      EXISTS (
//	        SELECT 1 FROM video_categories vc
//	        JOIN categories cat ON cat.id = vc.category_id
//	        WHERE vc.video_id = v.id
//	          AND LOWER(cat.name) LIKE '%' || LOWER(TRIM($1)) || '%'
//	      )
//	    )
//	    OR (
//	      EXISTS (
//	        SELECT 1 FROM video_categories vc
//	        JOIN sub_categories sc ON sc.id = vc.sub_category_id
//	        WHERE vc.video_id = v.id
//	          AND LOWER(sc.name) LIKE '%' || LOWER(TRIM($1)) || '%'
//	      )
//	    )
//	  )
//	ORDER BY random()
//	LIMIT $2 OFFSET $3
//
// ) AS sub
// JOIN videos v ON v.id = sub.id            ----How to aggregate ticks into candle in real system, and add resistance to our model
// JOIN channels c ON c.id = v.channel_id;
func (q *Queries) GetVideosWithKeywordFilter(ctx context.Context, arg GetVideosWithKeywordFilterParams) ([]GetVideosWithKeywordFilterRow, error) {
	rows, err := q.db.Query(ctx, getVideosWithKeywordFilter,
		arg.Btrim,
		arg.Limit,
		arg.Offset,
		arg.ID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVideosWithKeywordFilterRow{}
	for rows.Next() {
		var i GetVideosWithKeywordFilterRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Views,
			&i.DurationNs,
			&i.UploadedAt,
			&i.ChannelID,
			&i.ChannelName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVideoStatus = `-- name: SetVideoStatus :exec
UPDATE videos
SET status = $2
WHERE id = $1
`

type SetVideoStatusParams struct {
	ID     string          `json:"id"`
	Status NullVideoStatus `json:"status"`
}

func (q *Queries) SetVideoStatus(ctx context.Context, arg SetVideoStatusParams) error {
	_, err := q.db.Exec(ctx, setVideoStatus, arg.ID, arg.Status)
	return err
}

const updateVideo = `-- name: UpdateVideo :one
UPDATE videos
SET title = $2, description = $3, duration = $4
WHERE id = $1
RETURNING id, total_segment, received_s, title, status, visibility, description, uploaded_at, duration, views, likes, dislikes, channel_id, search_vector, title_tsvector
`

type UpdateVideoParams struct {
	ID          string          `json:"id"`
	Title       string          `json:"title"`
	Description pgtype.Text     `json:"description"`
	Duration    pgtype.Interval `json:"duration"`
}

func (q *Queries) UpdateVideo(ctx context.Context, arg UpdateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, updateVideo,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Duration,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.TotalSegment,
		&i.ReceivedS,
		&i.Title,
		&i.Status,
		&i.Visibility,
		&i.Description,
		&i.UploadedAt,
		&i.Duration,
		&i.Views,
		&i.Likes,
		&i.Dislikes,
		&i.ChannelID,
		&i.SearchVector,
		&i.TitleTsvector,
	)
	return i, err
}

const updateVideoDuration = `-- name: UpdateVideoDuration :exec
UPDATE videos
SET duration = $2::interval
WHERE id = $1
`

type UpdateVideoDurationParams struct {
	ID      string          `json:"id"`
	Column2 pgtype.Interval `json:"column_2"`
}

func (q *Queries) UpdateVideoDuration(ctx context.Context, arg UpdateVideoDurationParams) error {
	_, err := q.db.Exec(ctx, updateVideoDuration, arg.ID, arg.Column2)
	return err
}
