// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: streams.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createStream = `-- name: CreateStream :exec
INSERT INTO streams (id, title, stream_key, status) 
VALUES ($1, $2, $3, 'ready')
`

type CreateStreamParams struct {
	ID        string         `json:"id"`
	Title     sql.NullString `json:"title"`
	StreamKey sql.NullString `json:"stream_key"`
}

func (q *Queries) CreateStream(ctx context.Context, arg CreateStreamParams) error {
	_, err := q.db.ExecContext(ctx, createStream, arg.ID, arg.Title, arg.StreamKey)
	return err
}

const getConnectionQuality = `-- name: GetConnectionQuality :one
SELECT COALESCE(connection_quality, 'good') as connection_quality
FROM streams 
WHERE id = $1
`

func (q *Queries) GetConnectionQuality(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getConnectionQuality, id)
	var connection_quality string
	err := row.Scan(&connection_quality)
	return connection_quality, err
}

const getStaleStreams = `-- name: GetStaleStreams :many
SELECT id 
FROM streams 
WHERE status = 'live' 
AND last_heartbeat < NOW() - INTERVAL '60 seconds'
`

func (q *Queries) GetStaleStreams(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getStaleStreams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStream = `-- name: GetStream :one
SELECT id, title, stream_key, status, 
       COALESCE(start_time, NOW()) as start_time, 
       viewer_count 
FROM streams 
WHERE id = $1
`

type GetStreamRow struct {
	ID          string         `json:"id"`
	Title       sql.NullString `json:"title"`
	StreamKey   sql.NullString `json:"stream_key"`
	Status      sql.NullString `json:"status"`
	StartTime   sql.NullTime   `json:"start_time"`
	ViewerCount sql.NullInt32  `json:"viewer_count"`
}

func (q *Queries) GetStream(ctx context.Context, id string) (GetStreamRow, error) {
	row := q.db.QueryRowContext(ctx, getStream, id)
	var i GetStreamRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.StreamKey,
		&i.Status,
		&i.StartTime,
		&i.ViewerCount,
	)
	return i, err
}

const getStreamByKey = `-- name: GetStreamByKey :one
SELECT id FROM streams 
WHERE stream_key = $1 AND status = 'ready'
`

func (q *Queries) GetStreamByKey(ctx context.Context, streamKey sql.NullString) (string, error) {
	row := q.db.QueryRowContext(ctx, getStreamByKey, streamKey)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getStreamHealth = `-- name: GetStreamHealth :one
SELECT status, 
       COALESCE(connection_quality, 'unknown') as connection_quality,
       COALESCE(packet_loss_percent, 0) as packet_loss_percent,
       COALESCE(current_bitrate, 0) as current_bitrate,
       COALESCE(last_heartbeat, NOW()) as last_heartbeat,
       COALESCE(reconnect_attempts, 0) as reconnect_attempts,
       COALESCE(start_time, NOW()) as start_time
FROM streams 
WHERE id = $1
`

type GetStreamHealthRow struct {
	Status            sql.NullString `json:"status"`
	ConnectionQuality string         `json:"connection_quality"`
	PacketLossPercent float64        `json:"packet_loss_percent"`
	CurrentBitrate    int64          `json:"current_bitrate"`
	LastHeartbeat     sql.NullTime   `json:"last_heartbeat"`
	ReconnectAttempts int32          `json:"reconnect_attempts"`
	StartTime         sql.NullTime   `json:"start_time"`
}

func (q *Queries) GetStreamHealth(ctx context.Context, id string) (GetStreamHealthRow, error) {
	row := q.db.QueryRowContext(ctx, getStreamHealth, id)
	var i GetStreamHealthRow
	err := row.Scan(
		&i.Status,
		&i.ConnectionQuality,
		&i.PacketLossPercent,
		&i.CurrentBitrate,
		&i.LastHeartbeat,
		&i.ReconnectAttempts,
		&i.StartTime,
	)
	return i, err
}

const insertConnectionLog = `-- name: InsertConnectionLog :exec
INSERT INTO connection_logs (stream_id, event_type, details)
VALUES ($1, $2, $3)
`

type InsertConnectionLogParams struct {
	StreamID  sql.NullString        `json:"stream_id"`
	EventType sql.NullString        `json:"event_type"`
	Details   pqtype.NullRawMessage `json:"details"`
}

func (q *Queries) InsertConnectionLog(ctx context.Context, arg InsertConnectionLogParams) error {
	_, err := q.db.ExecContext(ctx, insertConnectionLog, arg.StreamID, arg.EventType, arg.Details)
	return err
}

const insertStreamAnalytics = `-- name: InsertStreamAnalytics :exec
INSERT INTO stream_analytics (stream_id, bitrate, fps)
VALUES ($1, $2, $3)
`

type InsertStreamAnalyticsParams struct {
	StreamID sql.NullString `json:"stream_id"`
	Bitrate  sql.NullInt64  `json:"bitrate"`
	Fps      sql.NullInt32  `json:"fps"`
}

func (q *Queries) InsertStreamAnalytics(ctx context.Context, arg InsertStreamAnalyticsParams) error {
	_, err := q.db.ExecContext(ctx, insertStreamAnalytics, arg.StreamID, arg.Bitrate, arg.Fps)
	return err
}

const listStreams = `-- name: ListStreams :many
SELECT id, title, status, 
       COALESCE(start_time, NOW()) as start_time, 
       viewer_count 
FROM streams 
ORDER BY created_at DESC 
LIMIT 50
`

type ListStreamsRow struct {
	ID          string         `json:"id"`
	Title       sql.NullString `json:"title"`
	Status      sql.NullString `json:"status"`
	StartTime   sql.NullTime   `json:"start_time"`
	ViewerCount sql.NullInt32  `json:"viewer_count"`
}

func (q *Queries) ListStreams(ctx context.Context) ([]ListStreamsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStreams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStreamsRow
	for rows.Next() {
		var i ListStreamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.StartTime,
			&i.ViewerCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnectionQuality = `-- name: UpdateConnectionQuality :exec
UPDATE streams SET connection_quality = $1 WHERE id = $2
`

type UpdateConnectionQualityParams struct {
	ConnectionQuality sql.NullString `json:"connection_quality"`
	ID                string         `json:"id"`
}

func (q *Queries) UpdateConnectionQuality(ctx context.Context, arg UpdateConnectionQualityParams) error {
	_, err := q.db.ExecContext(ctx, updateConnectionQuality, arg.ConnectionQuality, arg.ID)
	return err
}

const updateStreamEnded = `-- name: UpdateStreamEnded :exec
UPDATE streams 
SET status = 'ended', 
    end_time = $1 
WHERE id = $2
`

type UpdateStreamEndedParams struct {
	EndTime sql.NullTime `json:"end_time"`
	ID      string       `json:"id"`
}

func (q *Queries) UpdateStreamEnded(ctx context.Context, arg UpdateStreamEndedParams) error {
	_, err := q.db.ExecContext(ctx, updateStreamEnded, arg.EndTime, arg.ID)
	return err
}

const updateStreamReconnecting = `-- name: UpdateStreamReconnecting :exec
UPDATE streams 
SET status = 'reconnecting',
    reconnect_attempts = $1 
WHERE id = $2
`

type UpdateStreamReconnectingParams struct {
	ReconnectAttempts sql.NullInt32 `json:"reconnect_attempts"`
	ID                string        `json:"id"`
}

func (q *Queries) UpdateStreamReconnecting(ctx context.Context, arg UpdateStreamReconnectingParams) error {
	_, err := q.db.ExecContext(ctx, updateStreamReconnecting, arg.ReconnectAttempts, arg.ID)
	return err
}

const updateStreamStats = `-- name: UpdateStreamStats :exec
UPDATE streams 
SET last_heartbeat = $1,
    connection_quality = $2,
    packet_loss_percent = $3,
    current_bitrate = $4
WHERE id = $5
`

type UpdateStreamStatsParams struct {
	LastHeartbeat     sql.NullTime   `json:"last_heartbeat"`
	ConnectionQuality sql.NullString `json:"connection_quality"`
	PacketLossPercent sql.NullString `json:"packet_loss_percent"`
	CurrentBitrate    sql.NullInt64  `json:"current_bitrate"`
	ID                string         `json:"id"`
}

func (q *Queries) UpdateStreamStats(ctx context.Context, arg UpdateStreamStatsParams) error {
	_, err := q.db.ExecContext(ctx, updateStreamStats,
		arg.LastHeartbeat,
		arg.ConnectionQuality,
		arg.PacketLossPercent,
		arg.CurrentBitrate,
		arg.ID,
	)
	return err
}

const updateStreamStatus = `-- name: UpdateStreamStatus :exec
UPDATE streams SET status = $1 WHERE id = $2
`

type UpdateStreamStatusParams struct {
	Status sql.NullString `json:"status"`
	ID     string         `json:"id"`
}

func (q *Queries) UpdateStreamStatus(ctx context.Context, arg UpdateStreamStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateStreamStatus, arg.Status, arg.ID)
	return err
}

const updateStreamStatusWithEndTime = `-- name: UpdateStreamStatusWithEndTime :exec
UPDATE streams 
SET status = $1, 
    end_time = $2 
WHERE id = $3
`

type UpdateStreamStatusWithEndTimeParams struct {
	Status  sql.NullString `json:"status"`
	EndTime sql.NullTime   `json:"end_time"`
	ID      string         `json:"id"`
}

func (q *Queries) UpdateStreamStatusWithEndTime(ctx context.Context, arg UpdateStreamStatusWithEndTimeParams) error {
	_, err := q.db.ExecContext(ctx, updateStreamStatusWithEndTime, arg.Status, arg.EndTime, arg.ID)
	return err
}

const updateStreamTimeout = `-- name: UpdateStreamTimeout :exec
UPDATE streams 
SET status = 'timeout', 
    end_time = NOW() 
WHERE id = $1
`

func (q *Queries) UpdateStreamTimeout(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateStreamTimeout, id)
	return err
}

const updateStreamToLive = `-- name: UpdateStreamToLive :exec
UPDATE streams 
SET status = 'live', 
    start_time = $1, 
    last_heartbeat = $1,
    reconnect_attempts = 0 
WHERE id = $2
`

type UpdateStreamToLiveParams struct {
	StartTime sql.NullTime `json:"start_time"`
	ID        string       `json:"id"`
}

func (q *Queries) UpdateStreamToLive(ctx context.Context, arg UpdateStreamToLiveParams) error {
	_, err := q.db.ExecContext(ctx, updateStreamToLive, arg.StartTime, arg.ID)
	return err
}
