/**
 * @fileoverview gRPC-Web generated client stub for pb
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: Youtube_service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"
import * as rpc_playlist_pb from './rpc_playlist_pb'; // proto import: "rpc_playlist.proto"
import * as rpc_search_pb from './rpc_search_pb'; // proto import: "rpc_search.proto"
import * as rpc_Channel_pb from './rpc_Channel_pb'; // proto import: "rpc_Channel.proto"
import * as session_pb from './session_pb'; // proto import: "session.proto"
import * as rpc_comments_pb from './rpc_comments_pb'; // proto import: "rpc_comments.proto"
import * as rpc_category_pb from './rpc_category_pb'; // proto import: "rpc_category.proto"
import * as rpc_editvideo_pb from './rpc_editvideo_pb'; // proto import: "rpc_editvideo.proto"
import * as rpc_gif_pb from './rpc_gif_pb'; // proto import: "rpc_gif.proto"
import * as rpc_Home_pb from './rpc_Home_pb'; // proto import: "rpc_Home.proto"
import * as rpc_reaction_pb from './rpc_reaction_pb'; // proto import: "rpc_reaction.proto"
import * as rpc_stream_pb from './rpc_stream_pb'; // proto import: "rpc_stream.proto"
import * as rpc_preview_pb from './rpc_preview_pb'; // proto import: "rpc_preview.proto"
import * as rpc_subscription_pb from './rpc_subscription_pb'; // proto import: "rpc_subscription.proto"
import * as rpc_upload_pb from './rpc_upload_pb'; // proto import: "rpc_upload.proto"


export class YoutubeCloneClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGif = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/Gif',
    grpcWeb.MethodType.UNARY,
    rpc_gif_pb.GetGifRequest,
    rpc_gif_pb.GetGifResponse,
    (request: rpc_gif_pb.GetGifRequest) => {
      return request.serializeBinary();
    },
    rpc_gif_pb.GetGifResponse.deserializeBinary
  );

  gif(
    request: rpc_gif_pb.GetGifRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_gif_pb.GetGifResponse>;

  gif(
    request: rpc_gif_pb.GetGifRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_gif_pb.GetGifResponse) => void): grpcWeb.ClientReadableStream<rpc_gif_pb.GetGifResponse>;

  gif(
    request: rpc_gif_pb.GetGifRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_gif_pb.GetGifResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/Gif',
        request,
        metadata || {},
        this.methodDescriptorGif,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/Gif',
    request,
    metadata || {},
    this.methodDescriptorGif);
  }

  methodDescriptorSignin = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/Signin',
    grpcWeb.MethodType.UNARY,
    session_pb.SiginRequest,
    session_pb.SessionResponse,
    (request: session_pb.SiginRequest) => {
      return request.serializeBinary();
    },
    session_pb.SessionResponse.deserializeBinary
  );

  signin(
    request: session_pb.SiginRequest,
    metadata?: grpcWeb.Metadata | null): Promise<session_pb.SessionResponse>;

  signin(
    request: session_pb.SiginRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: session_pb.SessionResponse) => void): grpcWeb.ClientReadableStream<session_pb.SessionResponse>;

  signin(
    request: session_pb.SiginRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: session_pb.SessionResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/Signin',
        request,
        metadata || {},
        this.methodDescriptorSignin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/Signin',
    request,
    metadata || {},
    this.methodDescriptorSignin);
  }

  methodDescriptorCheckAuth = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/CheckAuth',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    session_pb.CheckAuthResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    session_pb.CheckAuthResponse.deserializeBinary
  );

  checkAuth(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<session_pb.CheckAuthResponse>;

  checkAuth(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: session_pb.CheckAuthResponse) => void): grpcWeb.ClientReadableStream<session_pb.CheckAuthResponse>;

  checkAuth(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: session_pb.CheckAuthResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/CheckAuth',
        request,
        metadata || {},
        this.methodDescriptorCheckAuth,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/CheckAuth',
    request,
    metadata || {},
    this.methodDescriptorCheckAuth);
  }

  methodDescriptorRefreshToken = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/RefreshToken',
    grpcWeb.MethodType.UNARY,
    session_pb.RefreshRequest,
    session_pb.SessionResponse,
    (request: session_pb.RefreshRequest) => {
      return request.serializeBinary();
    },
    session_pb.SessionResponse.deserializeBinary
  );

  refreshToken(
    request: session_pb.RefreshRequest,
    metadata?: grpcWeb.Metadata | null): Promise<session_pb.SessionResponse>;

  refreshToken(
    request: session_pb.RefreshRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: session_pb.SessionResponse) => void): grpcWeb.ClientReadableStream<session_pb.SessionResponse>;

  refreshToken(
    request: session_pb.RefreshRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: session_pb.SessionResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/RefreshToken',
        request,
        metadata || {},
        this.methodDescriptorRefreshToken,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/RefreshToken',
    request,
    metadata || {},
    this.methodDescriptorRefreshToken);
  }

  methodDescriptorSwitchChannel = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/SwitchChannel',
    grpcWeb.MethodType.UNARY,
    session_pb.SwitchChannelRequest,
    session_pb.SessionResponse,
    (request: session_pb.SwitchChannelRequest) => {
      return request.serializeBinary();
    },
    session_pb.SessionResponse.deserializeBinary
  );

  switchChannel(
    request: session_pb.SwitchChannelRequest,
    metadata?: grpcWeb.Metadata | null): Promise<session_pb.SessionResponse>;

  switchChannel(
    request: session_pb.SwitchChannelRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: session_pb.SessionResponse) => void): grpcWeb.ClientReadableStream<session_pb.SessionResponse>;

  switchChannel(
    request: session_pb.SwitchChannelRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: session_pb.SessionResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/SwitchChannel',
        request,
        metadata || {},
        this.methodDescriptorSwitchChannel,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/SwitchChannel',
    request,
    metadata || {},
    this.methodDescriptorSwitchChannel);
  }

  methodDescriptorUploadFiles = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/UploadFiles',
    grpcWeb.MethodType.UNARY,
    rpc_upload_pb.UploadFile,
    rpc_upload_pb.UploadFileResponse,
    (request: rpc_upload_pb.UploadFile) => {
      return request.serializeBinary();
    },
    rpc_upload_pb.UploadFileResponse.deserializeBinary
  );

  uploadFiles(
    request: rpc_upload_pb.UploadFile,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_upload_pb.UploadFileResponse>;

  uploadFiles(
    request: rpc_upload_pb.UploadFile,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_upload_pb.UploadFileResponse) => void): grpcWeb.ClientReadableStream<rpc_upload_pb.UploadFileResponse>;

  uploadFiles(
    request: rpc_upload_pb.UploadFile,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_upload_pb.UploadFileResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/UploadFiles',
        request,
        metadata || {},
        this.methodDescriptorUploadFiles,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/UploadFiles',
    request,
    metadata || {},
    this.methodDescriptorUploadFiles);
  }

  methodDescriptorGetVideos = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/GetVideos',
    grpcWeb.MethodType.SERVER_STREAMING,
    rpc_Home_pb.GetVideosRequest,
    rpc_Home_pb.GetVideosResponse,
    (request: rpc_Home_pb.GetVideosRequest) => {
      return request.serializeBinary();
    },
    rpc_Home_pb.GetVideosResponse.deserializeBinary
  );

  getVideos(
    request: rpc_Home_pb.GetVideosRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<rpc_Home_pb.GetVideosResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/pb.YoutubeClone/GetVideos',
      request,
      metadata || {},
      this.methodDescriptorGetVideos);
  }

  methodDescriptorsigninChannel = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/signinChannel',
    grpcWeb.MethodType.UNARY,
    rpc_Channel_pb.ChannelRequest,
    session_pb.SessionResponse,
    (request: rpc_Channel_pb.ChannelRequest) => {
      return request.serializeBinary();
    },
    session_pb.SessionResponse.deserializeBinary
  );

  signinChannel(
    request: rpc_Channel_pb.ChannelRequest,
    metadata?: grpcWeb.Metadata | null): Promise<session_pb.SessionResponse>;

  signinChannel(
    request: rpc_Channel_pb.ChannelRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: session_pb.SessionResponse) => void): grpcWeb.ClientReadableStream<session_pb.SessionResponse>;

  signinChannel(
    request: rpc_Channel_pb.ChannelRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: session_pb.SessionResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/signinChannel',
        request,
        metadata || {},
        this.methodDescriptorsigninChannel,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/signinChannel',
    request,
    metadata || {},
    this.methodDescriptorsigninChannel);
  }

  methodDescriptorCreateChannel = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/CreateChannel',
    grpcWeb.MethodType.UNARY,
    rpc_Channel_pb.CreateChannelRequest,
    rpc_Channel_pb.CreateChannelResponse,
    (request: rpc_Channel_pb.CreateChannelRequest) => {
      return request.serializeBinary();
    },
    rpc_Channel_pb.CreateChannelResponse.deserializeBinary
  );

  createChannel(
    request: rpc_Channel_pb.CreateChannelRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_Channel_pb.CreateChannelResponse>;

  createChannel(
    request: rpc_Channel_pb.CreateChannelRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_Channel_pb.CreateChannelResponse) => void): grpcWeb.ClientReadableStream<rpc_Channel_pb.CreateChannelResponse>;

  createChannel(
    request: rpc_Channel_pb.CreateChannelRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_Channel_pb.CreateChannelResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/CreateChannel',
        request,
        metadata || {},
        this.methodDescriptorCreateChannel,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/CreateChannel',
    request,
    metadata || {},
    this.methodDescriptorCreateChannel);
  }

  methodDescriptorListUserChannels = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/ListUserChannels',
    grpcWeb.MethodType.SERVER_STREAMING,
    google_protobuf_empty_pb.Empty,
    rpc_Channel_pb.ChannelResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    rpc_Channel_pb.ChannelResponse.deserializeBinary
  );

  listUserChannels(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<rpc_Channel_pb.ChannelResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/pb.YoutubeClone/ListUserChannels',
      request,
      metadata || {},
      this.methodDescriptorListUserChannels);
  }

  methodDescriptorUpdateChannel = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/UpdateChannel',
    grpcWeb.MethodType.UNARY,
    rpc_Channel_pb.UpdateChannelRequest,
    rpc_Channel_pb.UpdateChannelResponse,
    (request: rpc_Channel_pb.UpdateChannelRequest) => {
      return request.serializeBinary();
    },
    rpc_Channel_pb.UpdateChannelResponse.deserializeBinary
  );

  updateChannel(
    request: rpc_Channel_pb.UpdateChannelRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_Channel_pb.UpdateChannelResponse>;

  updateChannel(
    request: rpc_Channel_pb.UpdateChannelRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_Channel_pb.UpdateChannelResponse) => void): grpcWeb.ClientReadableStream<rpc_Channel_pb.UpdateChannelResponse>;

  updateChannel(
    request: rpc_Channel_pb.UpdateChannelRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_Channel_pb.UpdateChannelResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/UpdateChannel',
        request,
        metadata || {},
        this.methodDescriptorUpdateChannel,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/UpdateChannel',
    request,
    metadata || {},
    this.methodDescriptorUpdateChannel);
  }

  methodDescriptorGetChannel = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/GetChannel',
    grpcWeb.MethodType.UNARY,
    rpc_Channel_pb.ChannelRequest,
    rpc_Channel_pb.GetChannelResponse,
    (request: rpc_Channel_pb.ChannelRequest) => {
      return request.serializeBinary();
    },
    rpc_Channel_pb.GetChannelResponse.deserializeBinary
  );

  getChannel(
    request: rpc_Channel_pb.ChannelRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_Channel_pb.GetChannelResponse>;

  getChannel(
    request: rpc_Channel_pb.ChannelRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_Channel_pb.GetChannelResponse) => void): grpcWeb.ClientReadableStream<rpc_Channel_pb.GetChannelResponse>;

  getChannel(
    request: rpc_Channel_pb.ChannelRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_Channel_pb.GetChannelResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/GetChannel',
        request,
        metadata || {},
        this.methodDescriptorGetChannel,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/GetChannel',
    request,
    metadata || {},
    this.methodDescriptorGetChannel);
  }

  methodDescriptorGetManifest = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/GetManifest',
    grpcWeb.MethodType.UNARY,
    rpc_stream_pb.ManifestRequest,
    rpc_stream_pb.ManifestResponse,
    (request: rpc_stream_pb.ManifestRequest) => {
      return request.serializeBinary();
    },
    rpc_stream_pb.ManifestResponse.deserializeBinary
  );

  getManifest(
    request: rpc_stream_pb.ManifestRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_stream_pb.ManifestResponse>;

  getManifest(
    request: rpc_stream_pb.ManifestRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_stream_pb.ManifestResponse) => void): grpcWeb.ClientReadableStream<rpc_stream_pb.ManifestResponse>;

  getManifest(
    request: rpc_stream_pb.ManifestRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_stream_pb.ManifestResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/GetManifest',
        request,
        metadata || {},
        this.methodDescriptorGetManifest,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/GetManifest',
    request,
    metadata || {},
    this.methodDescriptorGetManifest);
  }

  methodDescriptorStreamSegment = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/StreamSegment',
    grpcWeb.MethodType.SERVER_STREAMING,
    rpc_stream_pb.SegmentRequest,
    rpc_stream_pb.SegmentChunk,
    (request: rpc_stream_pb.SegmentRequest) => {
      return request.serializeBinary();
    },
    rpc_stream_pb.SegmentChunk.deserializeBinary
  );

  streamSegment(
    request: rpc_stream_pb.SegmentRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<rpc_stream_pb.SegmentChunk> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/pb.YoutubeClone/StreamSegment',
      request,
      metadata || {},
      this.methodDescriptorStreamSegment);
  }

  methodDescriptorCreateCategory = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/CreateCategory',
    grpcWeb.MethodType.UNARY,
    rpc_category_pb.CreateCategoryRequest,
    rpc_category_pb.CreateCategoryResponse,
    (request: rpc_category_pb.CreateCategoryRequest) => {
      return request.serializeBinary();
    },
    rpc_category_pb.CreateCategoryResponse.deserializeBinary
  );

  createCategory(
    request: rpc_category_pb.CreateCategoryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_category_pb.CreateCategoryResponse>;

  createCategory(
    request: rpc_category_pb.CreateCategoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_category_pb.CreateCategoryResponse) => void): grpcWeb.ClientReadableStream<rpc_category_pb.CreateCategoryResponse>;

  createCategory(
    request: rpc_category_pb.CreateCategoryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_category_pb.CreateCategoryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/CreateCategory',
        request,
        metadata || {},
        this.methodDescriptorCreateCategory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/CreateCategory',
    request,
    metadata || {},
    this.methodDescriptorCreateCategory);
  }

  methodDescriptorUpdateCategory = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/UpdateCategory',
    grpcWeb.MethodType.UNARY,
    rpc_category_pb.UpdateCategoryRequest,
    rpc_category_pb.UpdateCategoryResponse,
    (request: rpc_category_pb.UpdateCategoryRequest) => {
      return request.serializeBinary();
    },
    rpc_category_pb.UpdateCategoryResponse.deserializeBinary
  );

  updateCategory(
    request: rpc_category_pb.UpdateCategoryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_category_pb.UpdateCategoryResponse>;

  updateCategory(
    request: rpc_category_pb.UpdateCategoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_category_pb.UpdateCategoryResponse) => void): grpcWeb.ClientReadableStream<rpc_category_pb.UpdateCategoryResponse>;

  updateCategory(
    request: rpc_category_pb.UpdateCategoryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_category_pb.UpdateCategoryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/UpdateCategory',
        request,
        metadata || {},
        this.methodDescriptorUpdateCategory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/UpdateCategory',
    request,
    metadata || {},
    this.methodDescriptorUpdateCategory);
  }

  methodDescriptorListCategories = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/ListCategories',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    rpc_category_pb.ListCategoriesResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    rpc_category_pb.ListCategoriesResponse.deserializeBinary
  );

  listCategories(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_category_pb.ListCategoriesResponse>;

  listCategories(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_category_pb.ListCategoriesResponse) => void): grpcWeb.ClientReadableStream<rpc_category_pb.ListCategoriesResponse>;

  listCategories(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_category_pb.ListCategoriesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/ListCategories',
        request,
        metadata || {},
        this.methodDescriptorListCategories,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/ListCategories',
    request,
    metadata || {},
    this.methodDescriptorListCategories);
  }

  methodDescriptorDeleteCategory = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/DeleteCategory',
    grpcWeb.MethodType.UNARY,
    rpc_category_pb.DeleteCategoryRequest,
    google_protobuf_empty_pb.Empty,
    (request: rpc_category_pb.DeleteCategoryRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteCategory(
    request: rpc_category_pb.DeleteCategoryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteCategory(
    request: rpc_category_pb.DeleteCategoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteCategory(
    request: rpc_category_pb.DeleteCategoryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/DeleteCategory',
        request,
        metadata || {},
        this.methodDescriptorDeleteCategory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/DeleteCategory',
    request,
    metadata || {},
    this.methodDescriptorDeleteCategory);
  }

  methodDescriptorCreateSubcategory = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/CreateSubcategory',
    grpcWeb.MethodType.UNARY,
    rpc_category_pb.CreateSubcategoryRequest,
    rpc_category_pb.CreateSubcategoryResponse,
    (request: rpc_category_pb.CreateSubcategoryRequest) => {
      return request.serializeBinary();
    },
    rpc_category_pb.CreateSubcategoryResponse.deserializeBinary
  );

  createSubcategory(
    request: rpc_category_pb.CreateSubcategoryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_category_pb.CreateSubcategoryResponse>;

  createSubcategory(
    request: rpc_category_pb.CreateSubcategoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_category_pb.CreateSubcategoryResponse) => void): grpcWeb.ClientReadableStream<rpc_category_pb.CreateSubcategoryResponse>;

  createSubcategory(
    request: rpc_category_pb.CreateSubcategoryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_category_pb.CreateSubcategoryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/CreateSubcategory',
        request,
        metadata || {},
        this.methodDescriptorCreateSubcategory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/CreateSubcategory',
    request,
    metadata || {},
    this.methodDescriptorCreateSubcategory);
  }

  methodDescriptorUpdateSubcategory = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/UpdateSubcategory',
    grpcWeb.MethodType.UNARY,
    rpc_category_pb.UpdateSubcategoryRequest,
    rpc_category_pb.UpdateSubcategoryResponse,
    (request: rpc_category_pb.UpdateSubcategoryRequest) => {
      return request.serializeBinary();
    },
    rpc_category_pb.UpdateSubcategoryResponse.deserializeBinary
  );

  updateSubcategory(
    request: rpc_category_pb.UpdateSubcategoryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_category_pb.UpdateSubcategoryResponse>;

  updateSubcategory(
    request: rpc_category_pb.UpdateSubcategoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_category_pb.UpdateSubcategoryResponse) => void): grpcWeb.ClientReadableStream<rpc_category_pb.UpdateSubcategoryResponse>;

  updateSubcategory(
    request: rpc_category_pb.UpdateSubcategoryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_category_pb.UpdateSubcategoryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/UpdateSubcategory',
        request,
        metadata || {},
        this.methodDescriptorUpdateSubcategory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/UpdateSubcategory',
    request,
    metadata || {},
    this.methodDescriptorUpdateSubcategory);
  }

  methodDescriptorListSubcategories = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/ListSubcategories',
    grpcWeb.MethodType.UNARY,
    rpc_category_pb.ListSubcategoriesRequest,
    rpc_category_pb.ListSubcategoriesResponse,
    (request: rpc_category_pb.ListSubcategoriesRequest) => {
      return request.serializeBinary();
    },
    rpc_category_pb.ListSubcategoriesResponse.deserializeBinary
  );

  listSubcategories(
    request: rpc_category_pb.ListSubcategoriesRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_category_pb.ListSubcategoriesResponse>;

  listSubcategories(
    request: rpc_category_pb.ListSubcategoriesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_category_pb.ListSubcategoriesResponse) => void): grpcWeb.ClientReadableStream<rpc_category_pb.ListSubcategoriesResponse>;

  listSubcategories(
    request: rpc_category_pb.ListSubcategoriesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_category_pb.ListSubcategoriesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/ListSubcategories',
        request,
        metadata || {},
        this.methodDescriptorListSubcategories,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/ListSubcategories',
    request,
    metadata || {},
    this.methodDescriptorListSubcategories);
  }

  methodDescriptorDeleteSubcategory = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/DeleteSubcategory',
    grpcWeb.MethodType.UNARY,
    rpc_category_pb.DeleteSubcategoryRequest,
    google_protobuf_empty_pb.Empty,
    (request: rpc_category_pb.DeleteSubcategoryRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteSubcategory(
    request: rpc_category_pb.DeleteSubcategoryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteSubcategory(
    request: rpc_category_pb.DeleteSubcategoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteSubcategory(
    request: rpc_category_pb.DeleteSubcategoryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/DeleteSubcategory',
        request,
        metadata || {},
        this.methodDescriptorDeleteSubcategory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/DeleteSubcategory',
    request,
    metadata || {},
    this.methodDescriptorDeleteSubcategory);
  }

  methodDescriptorAutocomplete = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/Autocomplete',
    grpcWeb.MethodType.UNARY,
    rpc_search_pb.AutocompleteRequest,
    rpc_search_pb.AutocompleteResponse,
    (request: rpc_search_pb.AutocompleteRequest) => {
      return request.serializeBinary();
    },
    rpc_search_pb.AutocompleteResponse.deserializeBinary
  );

  autocomplete(
    request: rpc_search_pb.AutocompleteRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_search_pb.AutocompleteResponse>;

  autocomplete(
    request: rpc_search_pb.AutocompleteRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_search_pb.AutocompleteResponse) => void): grpcWeb.ClientReadableStream<rpc_search_pb.AutocompleteResponse>;

  autocomplete(
    request: rpc_search_pb.AutocompleteRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_search_pb.AutocompleteResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/Autocomplete',
        request,
        metadata || {},
        this.methodDescriptorAutocomplete,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/Autocomplete',
    request,
    metadata || {},
    this.methodDescriptorAutocomplete);
  }

  methodDescriptorSearch = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/Search',
    grpcWeb.MethodType.UNARY,
    rpc_search_pb.SearchRequest,
    rpc_search_pb.SearchResponse,
    (request: rpc_search_pb.SearchRequest) => {
      return request.serializeBinary();
    },
    rpc_search_pb.SearchResponse.deserializeBinary
  );

  search(
    request: rpc_search_pb.SearchRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_search_pb.SearchResponse>;

  search(
    request: rpc_search_pb.SearchRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_search_pb.SearchResponse) => void): grpcWeb.ClientReadableStream<rpc_search_pb.SearchResponse>;

  search(
    request: rpc_search_pb.SearchRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_search_pb.SearchResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/Search',
        request,
        metadata || {},
        this.methodDescriptorSearch,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/Search',
    request,
    metadata || {},
    this.methodDescriptorSearch);
  }

  methodDescriptorUpdateVideoDetails = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/UpdateVideoDetails',
    grpcWeb.MethodType.UNARY,
    rpc_editvideo_pb.EditeVideoDetailsRequest,
    rpc_editvideo_pb.VideoDetailsResponse,
    (request: rpc_editvideo_pb.EditeVideoDetailsRequest) => {
      return request.serializeBinary();
    },
    rpc_editvideo_pb.VideoDetailsResponse.deserializeBinary
  );

  updateVideoDetails(
    request: rpc_editvideo_pb.EditeVideoDetailsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_editvideo_pb.VideoDetailsResponse>;

  updateVideoDetails(
    request: rpc_editvideo_pb.EditeVideoDetailsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_editvideo_pb.VideoDetailsResponse) => void): grpcWeb.ClientReadableStream<rpc_editvideo_pb.VideoDetailsResponse>;

  updateVideoDetails(
    request: rpc_editvideo_pb.EditeVideoDetailsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_editvideo_pb.VideoDetailsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/UpdateVideoDetails',
        request,
        metadata || {},
        this.methodDescriptorUpdateVideoDetails,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/UpdateVideoDetails',
    request,
    metadata || {},
    this.methodDescriptorUpdateVideoDetails);
  }

  methodDescriptorGetVideoDetails = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/GetVideoDetails',
    grpcWeb.MethodType.UNARY,
    rpc_editvideo_pb.GetVideoDetailRequest,
    rpc_editvideo_pb.VideoDetailsResponse,
    (request: rpc_editvideo_pb.GetVideoDetailRequest) => {
      return request.serializeBinary();
    },
    rpc_editvideo_pb.VideoDetailsResponse.deserializeBinary
  );

  getVideoDetails(
    request: rpc_editvideo_pb.GetVideoDetailRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_editvideo_pb.VideoDetailsResponse>;

  getVideoDetails(
    request: rpc_editvideo_pb.GetVideoDetailRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_editvideo_pb.VideoDetailsResponse) => void): grpcWeb.ClientReadableStream<rpc_editvideo_pb.VideoDetailsResponse>;

  getVideoDetails(
    request: rpc_editvideo_pb.GetVideoDetailRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_editvideo_pb.VideoDetailsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/GetVideoDetails',
        request,
        metadata || {},
        this.methodDescriptorGetVideoDetails,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/GetVideoDetails',
    request,
    metadata || {},
    this.methodDescriptorGetVideoDetails);
  }

  methodDescriptorDeleteVideo = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/DeleteVideo',
    grpcWeb.MethodType.UNARY,
    rpc_editvideo_pb.DeletesVideoRequest,
    rpc_editvideo_pb.DeletesVideoResponse,
    (request: rpc_editvideo_pb.DeletesVideoRequest) => {
      return request.serializeBinary();
    },
    rpc_editvideo_pb.DeletesVideoResponse.deserializeBinary
  );

  deleteVideo(
    request: rpc_editvideo_pb.DeletesVideoRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_editvideo_pb.DeletesVideoResponse>;

  deleteVideo(
    request: rpc_editvideo_pb.DeletesVideoRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_editvideo_pb.DeletesVideoResponse) => void): grpcWeb.ClientReadableStream<rpc_editvideo_pb.DeletesVideoResponse>;

  deleteVideo(
    request: rpc_editvideo_pb.DeletesVideoRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_editvideo_pb.DeletesVideoResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/DeleteVideo',
        request,
        metadata || {},
        this.methodDescriptorDeleteVideo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/DeleteVideo',
    request,
    metadata || {},
    this.methodDescriptorDeleteVideo);
  }

  methodDescriptorGetkeyword = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/Getkeyword',
    grpcWeb.MethodType.UNARY,
    rpc_Home_pb.VideoContextRequest,
    rpc_Home_pb.RecommendedKeywordsResponse,
    (request: rpc_Home_pb.VideoContextRequest) => {
      return request.serializeBinary();
    },
    rpc_Home_pb.RecommendedKeywordsResponse.deserializeBinary
  );

  getkeyword(
    request: rpc_Home_pb.VideoContextRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_Home_pb.RecommendedKeywordsResponse>;

  getkeyword(
    request: rpc_Home_pb.VideoContextRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_Home_pb.RecommendedKeywordsResponse) => void): grpcWeb.ClientReadableStream<rpc_Home_pb.RecommendedKeywordsResponse>;

  getkeyword(
    request: rpc_Home_pb.VideoContextRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_Home_pb.RecommendedKeywordsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/Getkeyword',
        request,
        metadata || {},
        this.methodDescriptorGetkeyword,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/Getkeyword',
    request,
    metadata || {},
    this.methodDescriptorGetkeyword);
  }

  methodDescriptorVideoMetadata = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/VideoMetadata',
    grpcWeb.MethodType.UNARY,
    rpc_Home_pb.VideoDetailsRequest,
    rpc_Home_pb.MetadataResponse,
    (request: rpc_Home_pb.VideoDetailsRequest) => {
      return request.serializeBinary();
    },
    rpc_Home_pb.MetadataResponse.deserializeBinary
  );

  videoMetadata(
    request: rpc_Home_pb.VideoDetailsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_Home_pb.MetadataResponse>;

  videoMetadata(
    request: rpc_Home_pb.VideoDetailsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_Home_pb.MetadataResponse) => void): grpcWeb.ClientReadableStream<rpc_Home_pb.MetadataResponse>;

  videoMetadata(
    request: rpc_Home_pb.VideoDetailsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_Home_pb.MetadataResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/VideoMetadata',
        request,
        metadata || {},
        this.methodDescriptorVideoMetadata,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/VideoMetadata',
    request,
    metadata || {},
    this.methodDescriptorVideoMetadata);
  }

  methodDescriptorCreateComment = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/CreateComment',
    grpcWeb.MethodType.UNARY,
    rpc_comments_pb.PostCommentRequest,
    rpc_comments_pb.PostCommentResponse,
    (request: rpc_comments_pb.PostCommentRequest) => {
      return request.serializeBinary();
    },
    rpc_comments_pb.PostCommentResponse.deserializeBinary
  );

  createComment(
    request: rpc_comments_pb.PostCommentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_comments_pb.PostCommentResponse>;

  createComment(
    request: rpc_comments_pb.PostCommentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_comments_pb.PostCommentResponse) => void): grpcWeb.ClientReadableStream<rpc_comments_pb.PostCommentResponse>;

  createComment(
    request: rpc_comments_pb.PostCommentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_comments_pb.PostCommentResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/CreateComment',
        request,
        metadata || {},
        this.methodDescriptorCreateComment,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/CreateComment',
    request,
    metadata || {},
    this.methodDescriptorCreateComment);
  }

  methodDescriptorListComments = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/ListComments',
    grpcWeb.MethodType.UNARY,
    rpc_comments_pb.ListCommentsRequest,
    rpc_comments_pb.ListCommentsResponse,
    (request: rpc_comments_pb.ListCommentsRequest) => {
      return request.serializeBinary();
    },
    rpc_comments_pb.ListCommentsResponse.deserializeBinary
  );

  listComments(
    request: rpc_comments_pb.ListCommentsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_comments_pb.ListCommentsResponse>;

  listComments(
    request: rpc_comments_pb.ListCommentsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_comments_pb.ListCommentsResponse) => void): grpcWeb.ClientReadableStream<rpc_comments_pb.ListCommentsResponse>;

  listComments(
    request: rpc_comments_pb.ListCommentsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_comments_pb.ListCommentsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/ListComments',
        request,
        metadata || {},
        this.methodDescriptorListComments,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/ListComments',
    request,
    metadata || {},
    this.methodDescriptorListComments);
  }

  methodDescriptorGetCommentCount = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/GetCommentCount',
    grpcWeb.MethodType.UNARY,
    rpc_comments_pb.GetCommentCountRequest,
    rpc_comments_pb.GetCommentCountResponse,
    (request: rpc_comments_pb.GetCommentCountRequest) => {
      return request.serializeBinary();
    },
    rpc_comments_pb.GetCommentCountResponse.deserializeBinary
  );

  getCommentCount(
    request: rpc_comments_pb.GetCommentCountRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_comments_pb.GetCommentCountResponse>;

  getCommentCount(
    request: rpc_comments_pb.GetCommentCountRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_comments_pb.GetCommentCountResponse) => void): grpcWeb.ClientReadableStream<rpc_comments_pb.GetCommentCountResponse>;

  getCommentCount(
    request: rpc_comments_pb.GetCommentCountRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_comments_pb.GetCommentCountResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/GetCommentCount',
        request,
        metadata || {},
        this.methodDescriptorGetCommentCount,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/GetCommentCount',
    request,
    metadata || {},
    this.methodDescriptorGetCommentCount);
  }

  methodDescriptorEditcomment = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/Editcomment',
    grpcWeb.MethodType.UNARY,
    rpc_comments_pb.EditCommentRequest,
    rpc_comments_pb.Comment,
    (request: rpc_comments_pb.EditCommentRequest) => {
      return request.serializeBinary();
    },
    rpc_comments_pb.Comment.deserializeBinary
  );

  editcomment(
    request: rpc_comments_pb.EditCommentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_comments_pb.Comment>;

  editcomment(
    request: rpc_comments_pb.EditCommentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_comments_pb.Comment) => void): grpcWeb.ClientReadableStream<rpc_comments_pb.Comment>;

  editcomment(
    request: rpc_comments_pb.EditCommentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_comments_pb.Comment) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/Editcomment',
        request,
        metadata || {},
        this.methodDescriptorEditcomment,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/Editcomment',
    request,
    metadata || {},
    this.methodDescriptorEditcomment);
  }

  methodDescriptorReplies = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/Replies',
    grpcWeb.MethodType.UNARY,
    rpc_comments_pb.GetRepliesRequest,
    rpc_comments_pb.GetRepliesResponse,
    (request: rpc_comments_pb.GetRepliesRequest) => {
      return request.serializeBinary();
    },
    rpc_comments_pb.GetRepliesResponse.deserializeBinary
  );

  replies(
    request: rpc_comments_pb.GetRepliesRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_comments_pb.GetRepliesResponse>;

  replies(
    request: rpc_comments_pb.GetRepliesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_comments_pb.GetRepliesResponse) => void): grpcWeb.ClientReadableStream<rpc_comments_pb.GetRepliesResponse>;

  replies(
    request: rpc_comments_pb.GetRepliesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_comments_pb.GetRepliesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/Replies',
        request,
        metadata || {},
        this.methodDescriptorReplies,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/Replies',
    request,
    metadata || {},
    this.methodDescriptorReplies);
  }

  methodDescriptorDeleteComment = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/DeleteComment',
    grpcWeb.MethodType.UNARY,
    rpc_comments_pb.DeleteCommentRequest,
    google_protobuf_empty_pb.Empty,
    (request: rpc_comments_pb.DeleteCommentRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteComment(
    request: rpc_comments_pb.DeleteCommentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteComment(
    request: rpc_comments_pb.DeleteCommentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteComment(
    request: rpc_comments_pb.DeleteCommentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/DeleteComment',
        request,
        metadata || {},
        this.methodDescriptorDeleteComment,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/DeleteComment',
    request,
    metadata || {},
    this.methodDescriptorDeleteComment);
  }

  methodDescriptorReactToComment = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/ReactToComment',
    grpcWeb.MethodType.UNARY,
    rpc_reaction_pb.LikeCommentRequest,
    rpc_reaction_pb.LikeCommentResponse,
    (request: rpc_reaction_pb.LikeCommentRequest) => {
      return request.serializeBinary();
    },
    rpc_reaction_pb.LikeCommentResponse.deserializeBinary
  );

  reactToComment(
    request: rpc_reaction_pb.LikeCommentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_reaction_pb.LikeCommentResponse>;

  reactToComment(
    request: rpc_reaction_pb.LikeCommentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_reaction_pb.LikeCommentResponse) => void): grpcWeb.ClientReadableStream<rpc_reaction_pb.LikeCommentResponse>;

  reactToComment(
    request: rpc_reaction_pb.LikeCommentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_reaction_pb.LikeCommentResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/ReactToComment',
        request,
        metadata || {},
        this.methodDescriptorReactToComment,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/ReactToComment',
    request,
    metadata || {},
    this.methodDescriptorReactToComment);
  }

  methodDescriptorSubscribe = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/Subscribe',
    grpcWeb.MethodType.UNARY,
    rpc_subscription_pb.SubscribeRequest,
    google_protobuf_empty_pb.Empty,
    (request: rpc_subscription_pb.SubscribeRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  subscribe(
    request: rpc_subscription_pb.SubscribeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  subscribe(
    request: rpc_subscription_pb.SubscribeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  subscribe(
    request: rpc_subscription_pb.SubscribeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/Subscribe',
        request,
        metadata || {},
        this.methodDescriptorSubscribe,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/Subscribe',
    request,
    metadata || {},
    this.methodDescriptorSubscribe);
  }

  methodDescriptorUnsubscribe = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/Unsubscribe',
    grpcWeb.MethodType.UNARY,
    rpc_subscription_pb.SubscribeRequest,
    google_protobuf_empty_pb.Empty,
    (request: rpc_subscription_pb.SubscribeRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  unsubscribe(
    request: rpc_subscription_pb.SubscribeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  unsubscribe(
    request: rpc_subscription_pb.SubscribeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  unsubscribe(
    request: rpc_subscription_pb.SubscribeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/Unsubscribe',
        request,
        metadata || {},
        this.methodDescriptorUnsubscribe,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/Unsubscribe',
    request,
    metadata || {},
    this.methodDescriptorUnsubscribe);
  }

  methodDescriptorGetSubscriptionStatus = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/GetSubscriptionStatus',
    grpcWeb.MethodType.UNARY,
    rpc_subscription_pb.SubscribeRequest,
    rpc_subscription_pb.SubscriptionStatus,
    (request: rpc_subscription_pb.SubscribeRequest) => {
      return request.serializeBinary();
    },
    rpc_subscription_pb.SubscriptionStatus.deserializeBinary
  );

  getSubscriptionStatus(
    request: rpc_subscription_pb.SubscribeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_subscription_pb.SubscriptionStatus>;

  getSubscriptionStatus(
    request: rpc_subscription_pb.SubscribeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_subscription_pb.SubscriptionStatus) => void): grpcWeb.ClientReadableStream<rpc_subscription_pb.SubscriptionStatus>;

  getSubscriptionStatus(
    request: rpc_subscription_pb.SubscribeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_subscription_pb.SubscriptionStatus) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/GetSubscriptionStatus',
        request,
        metadata || {},
        this.methodDescriptorGetSubscriptionStatus,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/GetSubscriptionStatus',
    request,
    metadata || {},
    this.methodDescriptorGetSubscriptionStatus);
  }

  methodDescriptorListSubscriptions = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/ListSubscriptions',
    grpcWeb.MethodType.SERVER_STREAMING,
    google_protobuf_empty_pb.Empty,
    rpc_subscription_pb.SubscribersResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    rpc_subscription_pb.SubscribersResponse.deserializeBinary
  );

  listSubscriptions(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<rpc_subscription_pb.SubscribersResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/pb.YoutubeClone/ListSubscriptions',
      request,
      metadata || {},
      this.methodDescriptorListSubscriptions);
  }

  methodDescriptorSubscribed = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/Subscribed',
    grpcWeb.MethodType.SERVER_STREAMING,
    google_protobuf_empty_pb.Empty,
    rpc_subscription_pb.SubscribedResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    rpc_subscription_pb.SubscribedResponse.deserializeBinary
  );

  subscribed(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<rpc_subscription_pb.SubscribedResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/pb.YoutubeClone/Subscribed',
      request,
      metadata || {},
      this.methodDescriptorSubscribed);
  }

  methodDescriptorCreatePlaylist = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/CreatePlaylist',
    grpcWeb.MethodType.UNARY,
    rpc_playlist_pb.CreatePlaylistRequest,
    rpc_playlist_pb.Playlist,
    (request: rpc_playlist_pb.CreatePlaylistRequest) => {
      return request.serializeBinary();
    },
    rpc_playlist_pb.Playlist.deserializeBinary
  );

  createPlaylist(
    request: rpc_playlist_pb.CreatePlaylistRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_playlist_pb.Playlist>;

  createPlaylist(
    request: rpc_playlist_pb.CreatePlaylistRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_playlist_pb.Playlist) => void): grpcWeb.ClientReadableStream<rpc_playlist_pb.Playlist>;

  createPlaylist(
    request: rpc_playlist_pb.CreatePlaylistRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_playlist_pb.Playlist) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/CreatePlaylist',
        request,
        metadata || {},
        this.methodDescriptorCreatePlaylist,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/CreatePlaylist',
    request,
    metadata || {},
    this.methodDescriptorCreatePlaylist);
  }

  methodDescriptorGetPlaylist = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/GetPlaylist',
    grpcWeb.MethodType.UNARY,
    rpc_playlist_pb.GetPlaylistRequest,
    rpc_playlist_pb.Playlist,
    (request: rpc_playlist_pb.GetPlaylistRequest) => {
      return request.serializeBinary();
    },
    rpc_playlist_pb.Playlist.deserializeBinary
  );

  getPlaylist(
    request: rpc_playlist_pb.GetPlaylistRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_playlist_pb.Playlist>;

  getPlaylist(
    request: rpc_playlist_pb.GetPlaylistRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_playlist_pb.Playlist) => void): grpcWeb.ClientReadableStream<rpc_playlist_pb.Playlist>;

  getPlaylist(
    request: rpc_playlist_pb.GetPlaylistRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_playlist_pb.Playlist) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/GetPlaylist',
        request,
        metadata || {},
        this.methodDescriptorGetPlaylist,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/GetPlaylist',
    request,
    metadata || {},
    this.methodDescriptorGetPlaylist);
  }

  methodDescriptorListPlaylists = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/ListPlaylists',
    grpcWeb.MethodType.UNARY,
    rpc_playlist_pb.ListPlaylistsRequest,
    rpc_playlist_pb.ListPlaylistsResponse,
    (request: rpc_playlist_pb.ListPlaylistsRequest) => {
      return request.serializeBinary();
    },
    rpc_playlist_pb.ListPlaylistsResponse.deserializeBinary
  );

  listPlaylists(
    request: rpc_playlist_pb.ListPlaylistsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_playlist_pb.ListPlaylistsResponse>;

  listPlaylists(
    request: rpc_playlist_pb.ListPlaylistsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_playlist_pb.ListPlaylistsResponse) => void): grpcWeb.ClientReadableStream<rpc_playlist_pb.ListPlaylistsResponse>;

  listPlaylists(
    request: rpc_playlist_pb.ListPlaylistsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_playlist_pb.ListPlaylistsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/ListPlaylists',
        request,
        metadata || {},
        this.methodDescriptorListPlaylists,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/ListPlaylists',
    request,
    metadata || {},
    this.methodDescriptorListPlaylists);
  }

  methodDescriptorUpdatePlaylist = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/UpdatePlaylist',
    grpcWeb.MethodType.UNARY,
    rpc_playlist_pb.UpdatePlaylistRequest,
    rpc_playlist_pb.Playlist,
    (request: rpc_playlist_pb.UpdatePlaylistRequest) => {
      return request.serializeBinary();
    },
    rpc_playlist_pb.Playlist.deserializeBinary
  );

  updatePlaylist(
    request: rpc_playlist_pb.UpdatePlaylistRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_playlist_pb.Playlist>;

  updatePlaylist(
    request: rpc_playlist_pb.UpdatePlaylistRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_playlist_pb.Playlist) => void): grpcWeb.ClientReadableStream<rpc_playlist_pb.Playlist>;

  updatePlaylist(
    request: rpc_playlist_pb.UpdatePlaylistRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_playlist_pb.Playlist) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/UpdatePlaylist',
        request,
        metadata || {},
        this.methodDescriptorUpdatePlaylist,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/UpdatePlaylist',
    request,
    metadata || {},
    this.methodDescriptorUpdatePlaylist);
  }

  methodDescriptorDeletePlaylist = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/DeletePlaylist',
    grpcWeb.MethodType.UNARY,
    rpc_playlist_pb.DeletePlaylistRequest,
    google_protobuf_empty_pb.Empty,
    (request: rpc_playlist_pb.DeletePlaylistRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deletePlaylist(
    request: rpc_playlist_pb.DeletePlaylistRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deletePlaylist(
    request: rpc_playlist_pb.DeletePlaylistRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deletePlaylist(
    request: rpc_playlist_pb.DeletePlaylistRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/DeletePlaylist',
        request,
        metadata || {},
        this.methodDescriptorDeletePlaylist,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/DeletePlaylist',
    request,
    metadata || {},
    this.methodDescriptorDeletePlaylist);
  }

  methodDescriptorAddItem = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/AddItem',
    grpcWeb.MethodType.UNARY,
    rpc_playlist_pb.AddItemRequest,
    rpc_playlist_pb.PlaylistItem,
    (request: rpc_playlist_pb.AddItemRequest) => {
      return request.serializeBinary();
    },
    rpc_playlist_pb.PlaylistItem.deserializeBinary
  );

  addItem(
    request: rpc_playlist_pb.AddItemRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_playlist_pb.PlaylistItem>;

  addItem(
    request: rpc_playlist_pb.AddItemRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_playlist_pb.PlaylistItem) => void): grpcWeb.ClientReadableStream<rpc_playlist_pb.PlaylistItem>;

  addItem(
    request: rpc_playlist_pb.AddItemRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_playlist_pb.PlaylistItem) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/AddItem',
        request,
        metadata || {},
        this.methodDescriptorAddItem,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/AddItem',
    request,
    metadata || {},
    this.methodDescriptorAddItem);
  }

  methodDescriptorRemoveItem = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/RemoveItem',
    grpcWeb.MethodType.UNARY,
    rpc_playlist_pb.RemoveItemRequest,
    google_protobuf_empty_pb.Empty,
    (request: rpc_playlist_pb.RemoveItemRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  removeItem(
    request: rpc_playlist_pb.RemoveItemRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  removeItem(
    request: rpc_playlist_pb.RemoveItemRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  removeItem(
    request: rpc_playlist_pb.RemoveItemRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/RemoveItem',
        request,
        metadata || {},
        this.methodDescriptorRemoveItem,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/RemoveItem',
    request,
    metadata || {},
    this.methodDescriptorRemoveItem);
  }

  methodDescriptorMoveItem = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/MoveItem',
    grpcWeb.MethodType.UNARY,
    rpc_playlist_pb.MoveItemRequest,
    rpc_playlist_pb.PlaylistItem,
    (request: rpc_playlist_pb.MoveItemRequest) => {
      return request.serializeBinary();
    },
    rpc_playlist_pb.PlaylistItem.deserializeBinary
  );

  moveItem(
    request: rpc_playlist_pb.MoveItemRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_playlist_pb.PlaylistItem>;

  moveItem(
    request: rpc_playlist_pb.MoveItemRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_playlist_pb.PlaylistItem) => void): grpcWeb.ClientReadableStream<rpc_playlist_pb.PlaylistItem>;

  moveItem(
    request: rpc_playlist_pb.MoveItemRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_playlist_pb.PlaylistItem) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/MoveItem',
        request,
        metadata || {},
        this.methodDescriptorMoveItem,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/MoveItem',
    request,
    metadata || {},
    this.methodDescriptorMoveItem);
  }

  methodDescriptorListItems = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/ListItems',
    grpcWeb.MethodType.UNARY,
    rpc_playlist_pb.ListItemsRequest,
    rpc_playlist_pb.ListItemsResponse,
    (request: rpc_playlist_pb.ListItemsRequest) => {
      return request.serializeBinary();
    },
    rpc_playlist_pb.ListItemsResponse.deserializeBinary
  );

  listItems(
    request: rpc_playlist_pb.ListItemsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<rpc_playlist_pb.ListItemsResponse>;

  listItems(
    request: rpc_playlist_pb.ListItemsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: rpc_playlist_pb.ListItemsResponse) => void): grpcWeb.ClientReadableStream<rpc_playlist_pb.ListItemsResponse>;

  listItems(
    request: rpc_playlist_pb.ListItemsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: rpc_playlist_pb.ListItemsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.YoutubeClone/ListItems',
        request,
        metadata || {},
        this.methodDescriptorListItems,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.YoutubeClone/ListItems',
    request,
    metadata || {},
    this.methodDescriptorListItems);
  }

  methodDescriptorGetPreview = new grpcWeb.MethodDescriptor(
    '/pb.YoutubeClone/GetPreview',
    grpcWeb.MethodType.SERVER_STREAMING,
    rpc_preview_pb.PreviewRequest,
    rpc_preview_pb.PreviewResponse,
    (request: rpc_preview_pb.PreviewRequest) => {
      return request.serializeBinary();
    },
    rpc_preview_pb.PreviewResponse.deserializeBinary
  );

  getPreview(
    request: rpc_preview_pb.PreviewRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<rpc_preview_pb.PreviewResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/pb.YoutubeClone/GetPreview',
      request,
      metadata || {},
      this.methodDescriptorGetPreview);
  }

}

